# Site settings
title: Iran University of Science and Technology
course_name: Theory of Formal Languages and Automata
course_description: Automata theory is the study of abstract machines and automata, as well as the computational problems that can be solved using them. It is a theory in theoretical computer science and discrete mathematics. The word automata comes from the Greek word αὐτόματα, which means "self-making".The figure at right illustrates a finite-state machine, which belongs to a well-known type of automaton. This automaton consists of states and transitions. As the automaton sees a symbol of input, it makes a transition to another state, according to its transition function, which takes the current state and the recent symbol as its inputs.Automata theory is closely related to formal language theory. An automaton is a finite representation of a formal language that may be an infinite set. Automata are often classified by the class of formal languages they can recognize, typically illustrated by the Chomsky hierarchy, which describes the relations between various languages and kinds of formalized logics.Automata play a major role in theory of computation, compiler construction, artificial intelligence, parsing and formal verification.
course_semester: "Fall 2019"
description: |
    Instructor: Dr. Hossein Rahmani

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "https://zahra-amiri.github.io/Automata_Theory" # the subpath of your site, e.g. /blog/
url: "https://zahra-amiri.github.io/Automata_Theory/" # the base hostname & protocol for your site
syllabus: https://zahra-amiri.github.io/Automata_Theory//syllabus/
githubdir: 

# Author/user information
email: h_rahmani@iust.ac.ir
# twitter_username: broken_twitter 
# github_username:  broken_github
# authorurl: "http://borken-url.github.io"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
