# Site settings
title: Iran University of Science and Technology
course_name: Theory of Formal Languages and Automata
course_description: Course description.
course_semester: "Fall 2019"
description: اين درس درباره جنبه هاي نظري رشته مهندسي کامپيوتر است و ارتباط بين مسايل و زبان ها را مشخص
مي نمايد. مباح مورد بررسي شامل مدل هاي مختلف محاسباتي، توانايي محاسباتي اين مدل ها، بيان رسمي
مدل ها و گرامرها، خواص محاسباتي آنها و کاربردهاي آن ها است. ديگر مباح شامل مفاهيم محاسبه پذيري،
تصميم پذيري و تز چرچ و تورين در مورد الگوريتم هاست. اين درس دانش پايه براي درسهاي کامپايلر،
طراحي الگوريتم، نظريه محاسبات، و درسهاي مرتبط با توصيف و مدل سازي رسمي سيستم هاي کامپيوتري را
در بر مي گيرد.
    Instructor: Zhila Sadati

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "https://zahra-amiri.github.io/Automata_Theory" # the subpath of your site, e.g. /blog/
url: "https://zahra-amiri.github.io/Automata_Theory/" # the base hostname & protocol for your site
syllabus: https://zahra-amiri.github.io/Automata_Theory//syllabus/
githubdir: 

# Author/user information
email: instructor-first-name@iust.ac.ir
twitter_username: broken_twitter 
github_username:  broken_github
authorurl: "http://borken-url.github.io"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
